name: Build JAR

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-jar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.12.0
      with:
        gradle-version: '8.5'

    - name: Build Plugin
      run: gradle buildPlugin
    - name: Show build results
      run: |
        echo "=== Build completed ==="
        echo "JAR files:"
        find build/libs -name "*.jar" -type f | head -10
        echo "Plugin distributions:"
        find build/distributions -name "*.zip" -type f | head -5
        
    - name: Upload JAR files
      uses: actions/upload-artifact@v4
      with:
        name: jar-files-${{ github.run_number }}
        path: build/libs/*.jar
        retention-days: 90

    - name: Upload Plugin ZIP
      uses: actions/upload-artifact@v4
      with:
        name: plugin-zip-${{ github.run_number }}
        path: build/distributions/*.zip
        retention-days: 90
        
    - name: Create Release (for main/master branch)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}-${{ github.sha }}
        name: Auto Build ${{ github.run_number }}
        body: |
          自动构建 - 运行号: ${{ github.run_number }}
          提交: ${{ github.sha }}
          分支: ${{ github.ref_name }}
          构建时间: ${{ github.event.head_commit.timestamp }}
        files: |
          build/distributions/*.zip
          build/libs/*.jar
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 